### ISSUE TITLE
Include automatic related model lookup URL, file upload question.

### ISSUE THREAD

**Issue by laith43d** [vitalik/django-ninja#193] opened 2021-08-07 21:26 UTC
Hi Vitalik,

I would like to say again that this project doesn't stop surprising me on how many features are there, well done and well built.

I have three questions:

1. Is there a way to include related model field resource URL automatically, for example

```json
{
    "data": {
        "id": 2,
        "username": "x",
        "related_data": {
            "href": "related/data/url/2/with/model/id/path/param",
        }
}
```

2. How to build images/files absolute URLs on the fly during serialization, so I don't have to include them in the model as a property field?

3. How to upload multiple files, and accept other form parameters at the same time? I mean sending images and text fields at the same time. I tried to do so but I failed, for example, to update the user account as well as upload profile images in the same request, or create a product with all images uploaded all at once in the same request.

**Comment by vitalik** [comment] 2021-08-08 09:43
Hi @laith43d 

Will check 1 and 3 later

but as for 2 - create schema should handle image fields (turning them to urls)

```Python
from ninja.orm import create_schema 

MySchema = create_schema(MyModel, fields=['id', 'image'])
```

if image is an ImageField - it should return url (based on your MEDIA_URL setting it would be either absolute or relative to domain path)

**Comment by stephenrauch** [comment] 2021-09-07 23:56
Point 3 above is duplicate of #162

**Comment by saberworks** [comment] 2022-02-18 04:52
Regarding point 2: the "url" returned by an image field turns out to be just the path component. For example: `"/media/levels/screenshots/1392_1.jpg"`.

I would really like this to be a full url, including the scheme and hostname.  I am a relative beginner with python and django and django ninja.

I first tried to add a new `@property` to the model field, named `screenshot_1_url` so that I could implement the getter and modify the return value.  But inside the model, I don't know how to get access to the Request object, which would be needed to figure out a real url.

I then tried adding a "resolver" for the field, like this:

```
class LevelOut(ModelSchema):
    screenshot_1_url: str


    def resolve_screenshot_1_url(self, level):
        # need access to the request object again!        
        return level.screenshot_1
```

But I ran into the same problem, where I need access to the request object so I can use something like `request.build_absolute_uri(level.screenshot_1)`, but again I could not get access to it.

Do you have any suggestions?  I'm probably just missing something obvious because I'm a beginner.  Thanks!

**Comment by vitalik** [comment] 2022-02-18 07:21
@saberworks 

>> Regarding point 2: the "url" returned by an image field turns out to be just the path component. For example: "/media/levels/screenshots/1392_1.jpg".

here the django url resolving mechanism is working

if you need full url - make sure to put full url into `settings.MEDIA_URL`

```
MEDIA_URL = 'https://yourfulldomain.com/media/'
```

**Comment by saberworks** [comment] 2022-02-18 18:54
Thanks.  It's really odd that it returns path including `/media/` for screenshots but for FileField (which are also just uploads), it doesn't include the `/media/` directory (even though they are in `media/`).

In general, though the point stands for me, I need to be able to add more fields (that aren't necessarily in the database) when constructing the json.  I ended up doing this:

```
@api.get("/levels/{str:category}", response=typing.List[LevelOut])
def get_levels(request, category: str, order_by: str = "name"):

    # .. more code here ...

    # intentional closure around `request` and `cat_name`
    def add_extra(obj):
        obj.screenshot_1_url = screenshot_url(request, obj.screenshot_1)
        obj.screenshot_2_url = screenshot_url(request, obj.screenshot_2)
        obj.download_url = download_url(request, obj.file.url)
        obj.category_name = cat_name
        obj.level_url = level_url(request, obj.id)

        return obj

    return list(map(add_extra, levels))
```

I was surprised to find that I could not return the `map` directly (it's an iterable), but instead I had to wrap it in `list`.  I was surprised because the queryset was itself an iterable and that worked ok.

**Comment by vitalik** [comment] 2022-02-19 07:34
@saberworks 

1) media

this is actually [default django mediafiles behaviour ](https://docs.djangoproject.com/en/4.0/topics/files/)

2) about map

map is generally a iterable that can produce infinite amount of result (pydantic cannot really know this if your code made infinite iterator) more about that [here](https://pydantic-docs.helpmanual.io/usage/types/#infinite-generators)

**Closed** 2024-06-28 15:09 UTC
