### ISSUE TITLE
Form data when uploading File Swagger Api

### ISSUE THREAD

**Issue by EnzoCp** [vitalik/django-ninja#134] opened 2021-05-11 00:25 UTC
When trying to send data with Form(...) while uploading data in the same API endpoint it swagger documentation fail to fetch:

![Screenshot from 2021-05-10 21-21-26](https://user-images.githubusercontent.com/65173811/117740138-31b51200-b1d6-11eb-9eef-c151f9762d30.png)
![Screenshot from 2021-05-10 21-21-39](https://user-images.githubusercontent.com/65173811/117740143-34b00280-b1d6-11eb-8f67-914719cbd325.png)
![Screenshot from 2021-05-10 21-21-59](https://user-images.githubusercontent.com/65173811/117740152-38438980-b1d6-11eb-95b1-f217c1bb781c.png)
![Screenshot from 2021-05-10 21-22-30](https://user-images.githubusercontent.com/65173811/117740153-3aa5e380-b1d6-11eb-89d2-03d604c5c5bb.png)

**Comment by hsjsjsj009** [comment] 2021-05-11 09:03
@EnzoCp I have the same problem like you, to make the combination possible, i create some "proxy" class and param class to override default File params in django ninja. The problem is in the open api generator only accept one model type.
```python
#params_model.py
from typing import Optional

from django.http import HttpRequest
from ninja import params_models, NinjaAPI
from ninja.types import DictStrAny
class FileModel(params_models.FileModel):
    @classmethod
    def get_request_data(
            cls, request: HttpRequest, api: "NinjaAPI", path_params: DictStrAny
    ) -> Optional[DictStrAny]:
        list_fields = getattr(cls, "_collection_fields", [])
        data_post = api.parser.parse_querydict(request.POST, list_fields, request)
        data_file = api.parser.parse_querydict(request.FILES, list_fields, request)
        return {**data_post, **data_file}
```

```python
#params.py
from ninja import params

from utils.ninja_addon.params_model import FileModel


class File(params.File):
    _model = FileModel
```

```python
#params_function.py
from typing import Any, Optional

from utils.ninja_addon import params


def File(
        default: Any,
        *,
        alias: Optional[str] = None,
        title: Optional[str] = None,
        description: Optional[str] = None,
        gt: Optional[float] = None,
        ge: Optional[float] = None,
        lt: Optional[float] = None,
        le: Optional[float] = None,
        min_length: Optional[int] = None,
        max_length: Optional[int] = None,
        regex: Optional[str] = None,
        deprecated: Optional[bool] = None,
        **extra: Any,
):
    return params.File(
        default,
        alias=alias,
        title=title,
        description=description,
        gt=gt,
        ge=ge,
        lt=lt,
        le=le,
        min_length=min_length,
        max_length=max_length,
        regex=regex,
        deprecated=deprecated,
        **extra,
    )
```

You can save it in a new package, and just use File(...) for your param value.

**Comment by EnzoCp** [comment] 2021-05-18 12:44
Thankyou, i will try it. The project is open source, why dont you try to send a PR?

> @EnzoCp I have the same problem like you, to make the combination possible, i create some "proxy" class and param class to override default File params in django ninja. The problem is in the open api generator only accept one model type.
> 
> ```python
> #params_model.py
> from typing import Optional
> 
> from django.http import HttpRequest
> from ninja import params_models, NinjaAPI
> from ninja.types import DictStrAny
> class FileModel(params_models.FileModel):
>     @classmethod
>     def get_request_data(
>             cls, request: HttpRequest, api: "NinjaAPI", path_params: DictStrAny
>     ) -> Optional[DictStrAny]:
>         list_fields = getattr(cls, "_collection_fields", [])
>         data_post = api.parser.parse_querydict(request.POST, list_fields, request)
>         data_file = api.parser.parse_querydict(request.FILES, list_fields, request)
>         return {**data_post, **data_file}
> ```
> 
> ```python
> #params.py
> from ninja import params
> 
> from utils.ninja_addon.params_model import FileModel
> 
> 
> class File(params.File):
>     _model = FileModel
> ```
> 
> ```python
> #params_function.py
> from typing import Any, Optional
> 
> from utils.ninja_addon import params
> 
> 
> def File(
>         default: Any,
>         *,
>         alias: Optional[str] = None,
>         title: Optional[str] = None,
>         description: Optional[str] = None,
>         gt: Optional[float] = None,
>         ge: Optional[float] = None,
>         lt: Optional[float] = None,
>         le: Optional[float] = None,
>         min_length: Optional[int] = None,
>         max_length: Optional[int] = None,
>         regex: Optional[str] = None,
>         deprecated: Optional[bool] = None,
>         **extra: Any,
> ):
>     return params.File(
>         default,
>         alias=alias,
>         title=title,
>         description=description,
>         gt=gt,
>         ge=ge,
>         lt=lt,
>         le=le,
>         min_length=min_length,
>         max_length=max_length,
>         regex=regex,
>         deprecated=deprecated,
>         **extra,
>     )
> ```
> 
> You can save it in a new package, and just use File(...) for your param value.
> @vitalik maybe you can fix problem.

**Comment by EnzoCp** [comment] 2021-07-11 21:58
> @EnzoCp I have the same problem like you, to make the combination possible, i create some "proxy" class and param class to override default File params in django ninja. The problem is in the open api generator only accept one model type.
> 
> ```python
> #params_model.py
> from typing import Optional
> 
> from django.http import HttpRequest
> from ninja import params_models, NinjaAPI
> from ninja.types import DictStrAny
> class FileModel(params_models.FileModel):
>     @classmethod
>     def get_request_data(
>             cls, request: HttpRequest, api: "NinjaAPI", path_params: DictStrAny
>     ) -> Optional[DictStrAny]:
>         list_fields = getattr(cls, "_collection_fields", [])
>         data_post = api.parser.parse_querydict(request.POST, list_fields, request)
>         data_file = api.parser.parse_querydict(request.FILES, list_fields, request)
>         return {**data_post, **data_file}
> ```
> 
> ```python
> #params.py
> from ninja import params
> 
> from utils.ninja_addon.params_model import FileModel
> 
> 
> class File(params.File):
>     _model = FileModel
> ```
> 
> ```python
> #params_function.py
> from typing import Any, Optional
> 
> from utils.ninja_addon import params
> 
> 
> def File(
>         default: Any,
>         *,
>         alias: Optional[str] = None,
>         title: Optional[str] = None,
>         description: Optional[str] = None,
>         gt: Optional[float] = None,
>         ge: Optional[float] = None,
>         lt: Optional[float] = None,
>         le: Optional[float] = None,
>         min_length: Optional[int] = None,
>         max_length: Optional[int] = None,
>         regex: Optional[str] = None,
>         deprecated: Optional[bool] = None,
>         **extra: Any,
> ):
>     return params.File(
>         default,
>         alias=alias,
>         title=title,
>         description=description,
>         gt=gt,
>         ge=ge,
>         lt=lt,
>         le=le,
>         min_length=min_length,
>         max_length=max_length,
>         regex=regex,
>         deprecated=deprecated,
>         **extra,
>     )
> ```
> 
> You can save it in a new package, and just use File(...) for your param value.
> @vitalik maybe you can fix problem.

i tried and still got the same error!

**Comment by stephenrauch** [comment] 2021-09-07 23:34
I think this is a duplicate of #162

**Closed** 2021-09-19 07:43 UTC
