### ISSUE TITLE
[BUG] TypeError: 'coroutine' object is not subscriptable [async pagination]

### ISSUE THREAD

**Issue by ddzyx** [vitalik/django-ninja#547] opened 2022-09-01 07:21 UTC
```Python
async def search(request, keywords: str):
    item = await sync_to_async(list)(Movie.objects.all())

    if item:
        return item
```

Error code after running

```
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\operation.py", line 99, in run
    result = self.view_func(request, **values)
  File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\pagination.py", line 145, in view_with_pagination
    result = paginator.paginate_queryset(
  File "D:\Program Files (x86)\Anaconda3\envs\django\lib\site-packages\ninja\pagination.py", line 69, in paginate_queryset
    "items": queryset[offset : offset + limit],
TypeError: 'coroutine' object is not subscriptable
```

**Comment by hiaselhans** [comment] 2022-09-04 16:35
i think this is a duplicate of #548

-> wrong return type for a `@pagination` decorated function

**Comment by chrismaille** [comment] 2022-10-17 23:07
In fact, the queryset parameter are receiving the decorated function, which was a coroutine, instead receiving the queryset which returns from this function/coroutine. Not sure why, but I believe this can be a bug indeed.

```python
from django.contrib.auth.models import Permission
from asgiref.sync import sync_to_async

# Pytest Asyncio
async def test_paginate(async_client):
    
    # Arrange
    class PermissionOut(ModelSchema):
        codename: str
        class Config:
            model = Permission
            model_fields = ["codename"]

    @api.get("/test", response=list[PermissionOut], auth=None)
    @paginate
    async def long_response(request):
        return await sync_to_async(list)(Permission.objects.all())

    # Act
    response = await async_client.get("/test")

    # Assert
    assert response.status_code == 200

```

Traceback

```plain
self = <ninja.pagination.LimitOffsetPagination object at 0x7f3ac6112c20>
queryset = <coroutine object test_paginate.<locals>.long_response at 0x7f3ac6140e40>
pagination = Input(limit=100, offset=0), params = {}, offset = 0, limit = 100

    def paginate_queryset(
        self,
        queryset: QuerySet,
        pagination: Input,
        **params: DictStrAny,
    ) -> Any:
        offset = pagination.offset
        limit: int = pagination.limit
        return {
>           "items": queryset[offset : offset + limit],
            "count": self._items_count(queryset),
        }  # noqa: E203
E       TypeError: 'coroutine' object is not subscriptable
```

**Comment by chrismaille** [comment] 2022-10-17 23:17
I think the issue is here:

https://github.com/vitalik/django-ninja/blob/3e9c10d5c8915a2ef76b08de8cdff98b45ca55f8/ninja/pagination.py#L143

Because `view_with_pagination` run the function syncronously, `items` is the coroutine.

**Comment by sunboy123** [comment] 2022-11-27 06:18
@chrismaille  i happend the same problem as you. can you solve it?

**Comment by chrismaille** [comment] 2022-11-29 20:55
@sunboy123 sure, I've created a async version for the decorator. Here is the code:

```python
import inspect
from functools import partial, wraps
from typing import Any, Callable, Tuple, Type

from asgiref.sync import sync_to_async
from django.db.models import QuerySet
from ninja.constants import NOT_SET
from ninja.pagination import LimitOffsetPagination, PaginationBase, make_response_paginated
from ninja.types import DictStrAny


class AsyncLimitOffsetPagination(LimitOffsetPagination):
    async def paginate_queryset(
        self,
        queryset: QuerySet,
        pagination: LimitOffsetPagination.Input,
        **params: DictStrAny,
    ):
        offset = pagination.offset
        limit: int = pagination.limit

        @sync_to_async
        def process_query_set():
            return {
                "items": queryset[offset : offset + limit] if queryset else [],
                "count": self._items_count(queryset) if queryset else 0,
            }

        return await process_query_set()


def apaginate(func_or_pgn_class: Any = NOT_SET, **paginator_params: DictStrAny) -> Callable:

    isfunction = inspect.isfunction(func_or_pgn_class)
    isnotset = func_or_pgn_class == NOT_SET

    pagination_class: Type[PaginationBase] = AsyncLimitOffsetPagination

    if isfunction:
        return _inject_pagination(func_or_pgn_class, pagination_class)

    if not isnotset:
        pagination_class = func_or_pgn_class

    async def wrapper(func: Callable) -> Any:
        return await _inject_pagination(func, pagination_class, **paginator_params)

    return wrapper


def _inject_pagination(
    func: Callable,
    paginator_class: Type[PaginationBase],
    **paginator_params: Any,
) -> Callable:
    paginator: PaginationBase = paginator_class(**paginator_params)

    @wraps(func)
    async def view_with_pagination(*args: Tuple[Any], **kwargs: DictStrAny) -> Any:
        pagination_params = kwargs.pop("ninja_pagination")
        if paginator.pass_parameter:
            kwargs[paginator.pass_parameter] = pagination_params

        items = await func(*args, **kwargs)

        result = await paginator.paginate_queryset(items, pagination=pagination_params, **kwargs)
        if paginator.Output:
            result[paginator.items_attribute] = list(result[paginator.items_attribute])
            # ^ forcing queryset evaluation #TODO: check why pydantic did not do it here
        return result

    view_with_pagination._ninja_contribute_args = [  # type: ignore
        (
            "ninja_pagination",
            paginator.Input,
            paginator.InputSource,
        ),
    ]

    if paginator.Output:
        view_with_pagination._ninja_contribute_to_operation = partial(  # type: ignore
            make_response_paginated,
            paginator,
        )

    return view_with_pagination

```

An example:

```python
from ninja import NinjaAPI, ModelSchema
from django.http import HttpRequest
from django.db import models, QuerySet

class MyModel(models.Model):
   foo = models.CharField(max_length=255)
   is_active = models.BooleanField(default=True)

class MyModelOut(ModelSchema):
  class Meta:
     model = MyModel
     model_fields = ["foo"]


api= NinjaAPI()

@api.get("/my-model", response=list[SchemaOut])
@apaginate
async def list_model(request: HttpRequest) -> QuerySet[MyModel]:
    return MyModel.objects.filter(is_active=True)
```

**Comment by sunboy123** [comment] 2022-12-02 11:04
@chrismaille thanks a lot .

**Comment by joaoflaviosantosmoniari** [comment] 2023-02-24 21:17
@chrismaille thanks a lot !!!

**Comment by babusqb** [comment] 2023-10-15 18:18
@vitalik Thanks for the great work! Is there any support for async paginate in the v1 expected?

**Comment by jamesrkiger** [comment] 2023-12-01 19:35
@vitalik I made some modifications to the code [suggested above](https://github.com/vitalik/django-ninja/issues/547#issuecomment-1331292288) for a project I am working on and got async pagination working.  We'd prefer to have these changes implemented upstream rather than copying in modified code and I would be happy to contribute to help make that happen. Would you be open to a PR for async pagination?

**Comment by dtasev** [comment] 2023-12-20 15:43
@jamesrkiger I don't think the repetition of a few lines should stop you from making the PR - especially when it's covered in tests. The merge of a sync and async coroutine to will probably require more lines of code than are duplicated, and if someone knows how to write it neatly then that would be a more visible place to reach that

**Comment by karambaq** [comment] 2023-12-21 09:57
> @sunboy123 sure, I've created a async version for the decorator. Here is the code:
> 
> ```python
> import inspect
> from functools import partial, wraps
> from typing import Any, Callable, Tuple, Type
> 
> from asgiref.sync import sync_to_async
> from django.db.models import QuerySet
> from ninja.constants import NOT_SET
> from ninja.pagination import LimitOffsetPagination, PaginationBase, make_response_paginated
> from ninja.types import DictStrAny
> 
> 
> class AsyncLimitOffsetPagination(LimitOffsetPagination):
>     async def paginate_queryset(
>         self,
>         queryset: QuerySet,
>         pagination: LimitOffsetPagination.Input,
>         **params: DictStrAny,
>     ):
>         offset = pagination.offset
>         limit: int = pagination.limit
> 
>         @sync_to_async
>         def process_query_set():
>             return {
>                 "items": queryset[offset : offset + limit] if queryset else [],
>                 "count": self._items_count(queryset) if queryset else 0,
>             }
> 
>         return await process_query_set()
> 
> 
> def apaginate(func_or_pgn_class: Any = NOT_SET, **paginator_params: DictStrAny) -> Callable:
> 
>     isfunction = inspect.isfunction(func_or_pgn_class)
>     isnotset = func_or_pgn_class == NOT_SET
> 
>     pagination_class: Type[PaginationBase] = AsyncLimitOffsetPagination
> 
>     if isfunction:
>         return _inject_pagination(func_or_pgn_class, pagination_class)
> 
>     if not isnotset:
>         pagination_class = func_or_pgn_class
> 
>     async def wrapper(func: Callable) -> Any:
>         return await _inject_pagination(func, pagination_class, **paginator_params)
> 
>     return wrapper
> 
> 
> def _inject_pagination(
>     func: Callable,
>     paginator_class: Type[PaginationBase],
>     **paginator_params: Any,
> ) -> Callable:
>     paginator: PaginationBase = paginator_class(**paginator_params)
> 
>     @wraps(func)
>     async def view_with_pagination(*args: Tuple[Any], **kwargs: DictStrAny) -> Any:
>         pagination_params = kwargs.pop("ninja_pagination")
>         if paginator.pass_parameter:
>             kwargs[paginator.pass_parameter] = pagination_params
> 
>         items = await func(*args, **kwargs)
> 
>         result = await paginator.paginate_queryset(items, pagination=pagination_params, **kwargs)
>         if paginator.Output:
>             result[paginator.items_attribute] = list(result[paginator.items_attribute])
>             # ^ forcing queryset evaluation #TODO: check why pydantic did not do it here
>         return result
> 
>     view_with_pagination._ninja_contribute_args = [  # type: ignore
>         (
>             "ninja_pagination",
>             paginator.Input,
>             paginator.InputSource,
>         ),
>     ]
> 
>     if paginator.Output:
>         view_with_pagination._ninja_contribute_to_operation = partial(  # type: ignore
>             make_response_paginated,
>             paginator,
>         )
> 
>     return view_with_pagination
> ```
> 
> An example:
> 
> ```python
> from django.http import HttpRequest
> from django.db import models, QuerySet
> from ninja import NinjaAPI, ModelSchema
> 
> class MyModel(models.Model):
>    foo = models.CharField(max_length=255)
>    is_active = models.BooleanField(default=True)
> 
> class MyModelOut(ModelSchema):
>   class Meta:
>      model = MyModel
>      model_fields = ["foo"]
> 
> 
> api= NinjaAPI()
> 
> @api.get("/my-model", response=list[MyModelOut])
> @apaginate
> async def list_model(request: HttpRequest) -> QuerySet[MyModel]:
>     return MyModel.objects.filter(is_active=True)
> ```
> 
> Please note, with this solution, if you need to use another Pagination class (like `AsyncLimitOffsetPagination`) you need to make that async compatible too.

Thanks for this. Which version of django-ninja you were using here?

I'm facing this problem with this code:

```python
   for callback in callbacks:
TypeError: 'functools.partial' object is not iterable

```

**Comment by kajiczech** [comment] 2024-04-05 10:52
@karambaq 
> I'm facing this problem with this code:
> 
> ```python
>    for callback in callbacks:
> TypeError: 'functools.partial' object is not iterable
> ```
 
I fixed it by adding a list of partial to `_ninja_contribute_to_operation` in `view_with_pagination()`
```python
view_with_pagination._ninja_contribute_to_operation = partial(  # type: ignore
            make_response_paginated,
            paginator,
        )

**Closed** 2024-04-30 11:42 UTC
