### ISSUE TITLE
Router@'/xxxx/' has already been attached to API NinjaAPI:1.0.0

### ISSUE THREAD

**Issue by Kenebehi** [vitalik/django-ninja#815] opened 2023-08-07 10:45 UTC
Hi all, I have a Django application that has one Router, I instantiate my Ninja API in the main app and add the router to the NinjaAPI,  run it with docker compose on local and it works however when I deploy to K8s it fails with error below.

I have one instance of NinjaAPI
And no tests

my stackoverflow link
https://stackoverflow.com/questions/76829725/django-error-ninja-errors-configerror-router-xxxxxxxx-has-already-been-att

I use gunicorn

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 597, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/aaa/aaa/aaa/urls.py", line 28, in <module>
    api.add_router("/xxx/", xxx)
  File "/usr/local/lib/python3.9/site-packages/ninja/main.py", line 367, in add_router
    self._routers.extend(router.build_routers(prefix))
  File "/usr/local/lib/python3.9/site-packages/ninja/router.py", line 366, in build_routers
    raise ConfigError(
ninja.errors.ConfigError: Router@'/xxx/' has already been attached to API NinjaAPI:1.0.0
```

**Comment by vitalik** [comment] 2023-08-07 10:57
@Kenebehi hard to tell without looking at code.. maybe you have some re-imports of API initializer ? 

I would suggest just making one import inside urls.py

**Comment by baseplate-admin** [comment] 2023-08-07 11:04
@Kenebehi, check if https://github.com/vitalik/django-ninja/issues/684#issuecomment-1505509879 solves this.

@vitalik duplicate of #684

**Comment by Kenebehi** [comment] 2023-08-07 11:59
Thanks @vitalik for responding but I have only one import

from my url.py

```
from authenticate.views import LoginView
from customer_explorer.views import NotificationUpdateView
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from ninja import NinjaAPI
from xxx.api import router as xxx_router

api = NinjaAPI()
api.add_router("/xxx_tool/", xxx_router)

urlpatterns = [
    path("api/", api.urls),
    path('admin/', admin.site.urls),
    path('xxx_tooll/', include('xxx.urls'), name='xxx')
```

**Comment by Kenebehi** [comment] 2023-08-07 12:07
Thanks @baseplate-admin it does not resolve it

PS, 
when I test on my local it works even two NinjaAPI instances in different files
However when I test on my k8s cluster with 4 replicas it fails

**Comment by Kenebehi** [comment] 2023-08-08 09:47
@vitalik @baseplate-admin please if you have any other ideas, I would appreciate thanks, it has confounded me.

**Comment by vitalik** [comment] 2023-08-08 11:36
@Kenebehi still not enogh info..

maybe something happens here ?

```Python
path('xxx_tooll/', include('xxx.urls'), name='xxx')
```

you can try debug it like this:


```Python


api = NinjaAPI()

try:
   print('Trying to add router...')
   api.add_router("/xxx_tool/", xxx_router)
except Exception as e:
    print(e)

```

and see who calls it and how many time ?

also show how you initialized you xxx_router   ? maybe you already passed api ?

**Comment by Kenebehi** [comment] 2023-08-08 14:36
Thanks @vitalik did the trick.

The issue was involved me using the wrong env variable for a database connection

I guess that repeated attempts at connection to the db somehow tried to intialize the NinjaAPi

**Closed** 2023-08-08 14:47 UTC
